apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: rapidserve-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80          
    targetPort: 80    
    protocol: TCP
    name: http
  selector:
    app: rapidserve-frontend     
