apiVersion: v1
kind: Service
metadata:
  name: rapidserve-upload
  labels:
    app: rapidserve-upload
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: reapidserve-upload  
